Spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    schema: classpath:/db/schema-h2.sql
    #    data: classpath:/db/data-h2.sql
    url: jdbc:h2:./h2/testdb
    username: sa
    password: sa
    platform: h2
    continue-on-error: true
  h2:
    # h2 web consloe 是一个数据库GUI管理应用，程序运行时，会自动启动h2 web consloe
    console:
      # 开启 h2 web console ，默认开启
      enabled: true
      # 可以通过 url/h2-console 访问 h2 web
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
